server:
  port: ${PORT:0}
spring:
  application:
    name: api-catalog
    rabbitmq:
      username: guest
      password: guest
      host: localhost
      port: 5672
  zipkin:
    baseUrl: http://localhost:9411