server:
  port: 0
spring:
  application:
    name: api-movie
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

resilience4j:
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
      instances:
        retryMovieService:
          base-config: default
          max-retry-attempts: 5
          wait-duration: 2s
          retry-exceptions:
            - java.net.ConnectException
  circuit-breaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
    instances:
      movieService:
        base-config: default
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        wait-duration-in-open-state: 1m
        failure-rate-threshold: 20
#Si quiere que ejecute con H2 y no con SQL descomente lo sigueinte, y comente el datasource anterior
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#    h2:
#      console:
#        enabled: true
#        path: /h2-console
#logging:
#  level:
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

