server:
  port: ${PORT:0}
spring:
  application:
    name: api-catalog
    rabbitmq:
      username: guest
      password: guest
      host: localhost
      port: 15672
  zipkin:
    baseUrl: http://localhost:9411
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017